name: Deploy Portfolio to GitHub Pages

uses: bitovi/github-actions-react-to-github-pages@v1.2.4

with:
  checkout: # optional, default is true
  checkout-filter: # optional
  checkout-sparse-checkout: # optional
  checkout-sparse-checkout-cone-mode: # optional, default is true
  path: build
#  install_command:
#  build_command:
#  caching:
          